### ISSUE TITLE
Hibernate 5 compatibility?

### ISSUE THREAD

**Issue by leojh** [The-Alchemist/hibernate-postgresql#1]
To be clear, this lib is not yet compatible with Hibernate 5, correct?

I'm seeing the that TheAlchemistHibernateIntegrator class does not match the Hibernate 5's interface.

**Comment by The-Alchemist** [comment]
Sorry, I fixed it locally but forgot to push it up to Central.  Version 1.0.16 should work with Hibernate 5.  Please don't hesitate to post back to see if it works for you.

**Comment by leojh** [comment]
Verified. Works on Hibernate 5.

**Comment by leojh** [comment]
Verified. Works on Hibernate 5.

**Comment by mikepc** [comment]
Might want to re-open this issue:
With Hibernate 5.3.7:

Receiver class com.github.thealchemist.pg_hibernate.HstoreType does not define or inherit an implementation of the resolved method abstract nullSafeSet(Ljava/sql/PreparedStatement

**Comment by The-Alchemist** [comment]
@mikepc : thanks for reporting, mike!  do you have a sample test case?  unit tests seem to pass.
