### ISSUE TITLE
Commas break HstoreHelper

### ISSUE THREAD

**Issue by blquinn** [The-Alchemist/hibernate-postgresql#10]
If you have a comma in An hstore key or value, Hstore helper will split on it, resulting in an index out of bounds error.

Why not use org.postgresql.util.HStoreConverter?

**Comment by The-Alchemist** [comment]
I didn't know about `org.postgresql.util.HStoreConverter`!  Thank you! 

Would you like to submit a PR?  I'll merge it quickly.

**Comment by blquinn** [comment]
Made a PR #11 that should fix the issue.

Thanks for the quick reply!

**Comment by The-Alchemist** [comment]
Merged!  Thank you!
