### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by paol** [The-Alchemist/hibernate-postgresql#12]
Could you please do a release of version 1.0.19? Maven central has 1.0.18 which doesn't have the Hibernate 5 support.

**Comment by The-Alchemist** [comment]
done!  it should show up on Maven Central within a few hours.

**Comment by paol** [comment]
The release hasn't hit maven central yet [1]. Something must have gone wrong.

[1] http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.the-alchemist%22%20AND%20a%3A%22hibernate-postgresql%22

**Comment by The-Alchemist** [comment]
Sorry, forgot to release the build from OSSRH.  Should be up soon.

**Comment by paol** [comment]
It's up now. Thanks a lot.

**Comment by The-Alchemist** [comment]
Sorry it took so long, and thanks for pointing it out!
